### ISSUE TITLE
Retrofit 1.9 Compatibility

### ISSUE THREAD

**Issue by Nsonni** [upnext/BeaconControl#34] opened 2016-09-28 12:22 UTC
Currently this SDK does not support Retrofit 1.9 as its using 2.0.0 beta 1.

Can we create a backwards compatible branch?

**Comment by jkurdel** [comment] 2016-09-29 04:35
Closing as a duplicate of https://github.com/upnext/BeaconControl_Android_SDK/issues/11

**Closed as completed by jkurdel** 2016-09-29 04:35 UTC

**Comment by Nsonni** [comment] 2016-09-29 05:44
Could you at least refer me to where this question has been answered?

**Comment by jkurdel** [comment] 2016-09-29 06:10
Hi @Nsonni

Sorry, I have referenced wrong issue (please see edited comment). I have closed this issue also because this is Rails project not Android SDK project.
