### ISSUE TITLE
Cannot upload coupon image through s2s API

### ISSUE THREAD

**Issue by otrebmuh** [upnext/BeaconControl#41] opened 2016-12-26 14:38 UTC
I am having problems uploading images through the s2s API (https://beaconcontrol.io/dev/backend/s2s_api_docs_v1/activities.html).

The documentation states the following:

 "image_attributes": {
        "id": 1,
        "type": "image",
        "file": *FILE*
      }

I am sending the file encoded as base64, and in the server logs I can see that it is received as I see the encoded image data.  As a note, I am sending the image data as follows:

"file": "iVBORw0KGgoAAAANSUhEUgAAAF8AA...."

There is, however something wrong as the server log shows file to be null as in the following example:

[DEBUG] SQL (0.5ms) INSERT INTO "coupon_images" ("file", "type", "coupon_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id" [["file", nil], ["type", "image"], ["coupon_id", 106], ["created_at", "2016-12-26 13:50:40.212766"], ["updated_at", "2016-12-26 13:50:40.212766"]]

What am I doing wrong?

Thank you and best regards,

Humberto

**Comment by jkurdel** [comment] 2017-01-03 18:22
Closing as a duplicate of https://github.com/upnext/BeaconControl/issues/40 issue

**Closed as completed by jkurdel** 2017-01-03 18:22 UTC
